SMAROMU-3 人事労務・入社手続き Testing と Storybook 中に毎回 mock API が必要、よくない、自動で mock API したい
ThaddeusJiang/spa-hr pull request #5
Opened 2022-06-24 08:41 UTC by thomaszdxsn

Ticket: https://nisshin30.backlog.com/view/SMAROMU-3#comment-108053980

2022-06-24 10:31 UTC, ThaddeusJiang commented on src/apis/todos/todos.ts
> +  return axios.get(`/todos/${id}`).then((res) => res.data);
我们推荐 async await 风格，不推荐 `.then`

2022-06-24 10:31 UTC, ThaddeusJiang commented on src/components/MembersCell/MembersCell.tsx
> +  if (memberLength === 0) return <Empty />;
```suggestion
  if (!members?.length) return <Empty />;
```

2022-06-24 10:31 UTC, ThaddeusJiang commented on src/components/TodoCell/TodoCell.tsx
> +  useQuery(["todo", id], () => getTodo(id));
```suggestion
  useQuery(["todos", id], () => getTodo(id));
```

2022-06-24 10:31 UTC, ThaddeusJiang commented on src/components/TodoCell/TodoCell.tsx
> +  // empty should redirect to 404 by client?
No

empty 就是 empty，404 是 error。

see: https://github.com/jiang-jifa/public_space/issues/58

2022-06-24 10:31 UTC, ThaddeusJiang commented on src/utils/testUtils.tsx
> +export const wrapper = ({ children }: { children: React.ReactNode }) => {
```suggestion
export const ReactQueryWrapper = ({ children }: { children: React.ReactNode }) => {
```

2022-06-24 10:33 UTC, ThaddeusJiang requested changes
@thomaszdxsn 代码基本上OK。

- 有几个小问题
- 代码有冲突
- CI 失败了

2022-06-24 10:50 UTC, thomaszdxsn commented on src/components/TodoCell/TodoCell.tsx
> +  // empty should redirect to 404 by client?
已修改

2022-06-24 10:50 UTC, thomaszdxsn commented on src/utils/testUtils.tsx
> +export const wrapper = ({ children }: { children: React.ReactNode }) => {
已修改

2022-06-24 10:50 UTC, thomaszdxsn commented on src/components/TodoCell/TodoCell.tsx
> +  useQuery(["todo", id], () => getTodo(id));
已修改

2022-06-24 10:50 UTC, thomaszdxsn commented on src/components/MembersCell/MembersCell.tsx
> +  if (memberLength === 0) return <Empty />;
已修改

2022-06-24 10:51 UTC, thomaszdxsn commented on src/apis/todos/todos.ts
> +  return axios.get(`/todos/${id}`).then((res) => res.data);
已修改

2022-06-24 10:56 UTC, thomaszdxsn commented
@ThaddeusJiang 蒋桑，CI 中 Vercel deploy fail 我看不到原因，点击 `details` 显示我没有权限

2022-06-27 06:44 UTC, ThaddeusJiang approved these changes
LGTM

2022-06-27 06:44 UTC, merged